Repository csound/csound, pull requests merged in 2025-09, with the labels that each got.

#2256 Xtratim in udos
  Engine/udo.c
  iOS/Csound-for-iOS/Csound-iOS-ObjC-Examples/CsoundObj/classes/.DS_Store
Labels: bug, release

#2261 Shadowing of implicit types
  Engine/csound_orc_semantics.c
  tests/commandline/test.py
  tests/commandline/test_shadowing_implicit.csd
Labels: bug

#2273 Update libogg to use github instead of gitlab for download
  platform/vcpkg/ports/libogg/portfile.cmake
  platform/vcpkg/ports/libogg/vcpkg.json
Labels: bug

#2293 Fixed issue #2291
  Engine/csound_orc_semantics.c
Labels: bug

#2289 Implementing #2288
  Engine/csound_orc_expressions.c
  Engine/csound_orc_semantics.c
  tests/commandline/test.py
  tests/commandline/test_shadowing_for_loop.csd
Labels: enhancement

#2286 Fix for opcodes with opt inputs only
  Top/main.c
  Top/opcode.c
  tests/commandline/test.py
  tests/commandline/test_opcode_with_opt_ins.csd
Labels: bug
